import type { Metadata } from "next";
import "./globals.css";
import { Barlow_Semi_Condensed } from 'next/font/google'


const barlowSemiCondensed = Barlow_Semi_Condensed({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], // Add weights you need
  variable: '--font-barlow',
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${barlowSemiCondensed.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
